- type: antag
  id: Nukeops
  name: roles-antag-nuclear-operative-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 14400 # 15h # Corvax-RoleTime
  - !type:DepartmentTimeRequirement
    department: Security
    time: 3600 # 5h # Corvax-RoleTime
  guides: [ NuclearOperatives ]

- type: antag
  id: NukeopsMedic
  name: roles-antag-nuclear-operative-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-agent-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 10800 # 15h # Corvax-RoleTime
  - !type:RoleTimeRequirement
    role: JobChemist
    time: 14400 # 10h # Corvax-RoleTime
  - !type:DepartmentTimeRequirement
    department: Security
    time: 3600 # 10h # Corvax-RoleTime
  guides: [ NuclearOperatives ]

- type: antag
  id: NukeopsCommander
  name: roles-antag-nuclear-operative-commander-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-commander-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 21600 # 30h # Corvax-RoleTime
  - !type:DepartmentTimeRequirement
    department: Security
    time: 10800 # 15h # Corvax-RoleTime
  # should be changed to nukie playtime when thats tracked (wyci)
  guides: [ NuclearOperatives ]

- type: startingGear
  id: SyndicateOperativeGearFullNoUplink
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicate
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    # outerClothing: ClothingOuterHardsuitSyndie
    shoes: ClothingShoesBootsCombatFilled
    id: SyndiPDA
    pocket2: PlushieCarp
    belt: ClothingBeltMilitaryWebbing
  storage:
    back:
    - WeaponPistolViper
    - PinpointerSyndicateNuclear
    - DeathAcidifierImplanter

#Nuclear Operative Gear
- type: startingGear
  id: SyndicateOperativeGearFull
  parent: SyndicateOperativeGearFullNoUplink
  equipment:
    pocket2: BaseUplinkRadio200TC

#Nuclear Operative Commander Gear
- type: startingGear
  id: SyndicateCommanderGearFull
  parent: SyndicateOperativeGearFull
  equipment:
    neck: SyndicateWhistle
    # outerClothing: ClothingOuterHardsuitSyndieCommander
    pocket2: BaseUplinkRadio200TCCommander
  inhand:
  - NukeOpsDeclarationOfWar
# ADT-NukieCommanderGear-tweak-start (если вписать тупо последнее, то остальное не заспавнится)
  storage:
    back:
    - WeaponPistolViper
    - PinpointerSyndicateNuclear
    - DeathAcidifierImplanter
# ADT-NukieCommanderGear-tweak-end

#Nuclear Operative Medic Gear
- type: startingGear
  id: SyndicateOperativeMedicFull
  parent: SyndicateOperativeGearFull
  equipment:
    eyes: ClothingEyesHudSyndicateAgent
    # outerClothing: ClothingOuterHardsuitSyndieMedic
    shoes: ClothingShoesBootsMagSyndie
    id: SyndiAgentPDA
    belt: ClothingBeltMilitaryWebbingMedFilled
    pocket2: BaseUplinkRadio200TCMedic
  storage:
    back:
    - SyndiHypo
    - SawAdvanced
    - Cautery
    - CombatKnife
    - WeaponPistolViper
    - PinpointerSyndicateNuclear
    - HandheldHealthAnalyzer
    - CombatMedipen
    - DeathAcidifierImplanter

#Lone Operative Gear
- type: startingGear
  id: SyndicateLoneOperativeGearFull
  parent: SyndicateOperativeGearFull
  equipment:
    pocket2: BaseUplinkRadio350TCLoneOps
